name: peckish_pdf
description: "peckish_pdf allows Flutter developers to add interactive PDFs to their Android and iOS apps."
version: 0.0.1
homepage: https://github.com/alokjha2/peckish_pdf
repository: https://github.com/alokjha2/peckish_pdf
issue_tracker: https://github.com/alokjha2/peckish_pdf/issues

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.yourdomain.peckish_pdf
        pluginClass: PeckishPdfPlugin
      ios:
        pluginClass: PeckishPdfPlugin

  uses-material-design: true
